name: expense_tracker
description: "A privacy-first, automated finance tracker."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  google_fonts: ^7.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^4.0.0+1
  drift_dev: ^2.30.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
